services:
  app:
    container_name: tms_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - postgres
  postgres:
    image: postgres
    container_name: tms_postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - $DB_PORT:5432
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
