services:
  postgres:
    image: postgres
    container_name: tms_postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - $DB_PORT:5432
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    networks:
      - postgres

  pgadmin:
    container_name: tms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "some@some.com"
      PGADMIN_DEFAULT_PASSWORD: $DB_PASSWORD
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pg:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 600M
    networks:
      - postgres

volumes:
  postgres:
  pg:

networks:
  postgres:
    driver: bridge
